export const ROUTES = {
    HOME: { name: 'Design Pattern Examples', route: 'home' },
    COLLAPSIBLE_APPBAR: { name: 'Collapsible', route: 'collapsible-appbar' },
    SEARCH_BAR: { name: 'Search', route: 'search-bar' },
    LOADING_STATES: { name: 'Loading States', route: 'loading-states' },
    FORM_VALIDATION: { name: 'Form Validation', route: 'form-validation' },
    FORMS_AND_VALIDATION: { name: 'Forms and Validation' },
    PASSWORD_VALIDATION: { name: 'Password', route: 'password' },
    FIXED_LENGTH_PASSCODE: { name: 'Fixed Length Passcode', route: 'fixed-length-passcode' },
    I18N: { name: 'Internationalization', route: 'internationalization' },
    ACTION_LIST: { name: 'Action List', route: 'action-list' },
    DATA_LIST: { name: 'Data List', route: 'data-list' },
    MULTISELECT_LIST: { name: 'Multiselect List', route: 'multiselect-list' },
    SORTABLE_LIST: { name: 'Sortable List', route: 'sortable-list' },
    STATUS_LIST: { name: 'Status List', route: 'status-list' },
    RESPONSIVE_TABLE: { name: 'Responsive Table', route: 'responsive-table' },
    BOTTOMSHEET: { name: 'Basic Bottom Sheet', route: 'bottomsheet' },
    COMPLEX_BOTTOMSHEET: { name: 'Complex Bottom Sheet', route: 'complex-bottomsheet' },
    DYNAMIC_STEPPER: { name: 'Dynamic Stepper', route: 'dynamic-stepper' },
};
