export const ROUTES = {
    HOME: { name: 'Design Pattern Examples', route: 'home' },
    COLLAPSIBLE_APPBAR: { name: 'Collapsible Appbar', route: 'collapsible-appbar' },
    SEARCH_BAR: { name: 'Search Bar', route: 'search-bar' },
    LOADING_STATES: { name: 'Loading States', route: 'loading-states' },
    FORM_VALIDATION: { name: 'Form Validation', route: 'form-validation' },
    I18N: { name: 'Internationalization', route: 'internationalization' },
    ACTION_LIST: { name: 'Action List', route: 'action-list' },
    DATA_LIST: { name: 'Data List', route: 'data-list' },
    MULTISELECT_LIST: { name: 'Multiselect List', route: 'mulstiselect-list' },
    SORTABLE_LIST: { name: 'Sortable List', route: 'sortable-list' },
    STATUS_LIST: { name: 'Status List', route: 'status-list' },
    RESPONSIVE_TABLE: { name: 'Responsive Table', route: 'responsive-table' },
    BOTTOMSHEET: { name: 'Bottomsheet', route: 'bottomsheet' },
    COMPLEX_BOTTOMSHEET: { name: 'Complex Bottomsheet', route: 'complex-bottomsheet' },
    DYNAMIC_STEPPER: { name: 'Dynamic Stepper', route: 'dynamic-stepper' },
};
